on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: "login to docker"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.TOCKEN }}

      - name: "buliding image"
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/task2 .

      - name: "pushing to docker hub" 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task2